# First load the module
#        module load snakemake
#
# usage: $ snakemake -np ../mapped_reads/A.bam
#          snakemake --cores 1 ../mapped_reads/A.bam


rule bwa_map:
    input:
        "../data/genome.fa",
        "../data/samples/A.fastq"
    output:
        "../mapped_reads/A.bam"
    shell:
        '''
    module load bwa-mem samtools
    bwa mem {input} | samtools view -Sb - > {output}
'''
