# First load the modules
#        module load snakemake samtools
#
# usage: $ snakemake -np mapped_reads/B.bam
#          snakemake -np mapped_reads/A.bam mapped_reads/B.bam
#          snakemake -np mapped_reads/{A,B}.bam


rule samtools_sort:
    input:
        "../mapped_reads/{sample}.bam"
    output:
        "../sorted_reads/{sample}.bam"
    shell:
    '''

        samtools sort -T sorted_reads/{wildcards.sample} -O bam {input} > {output}
    '''
