#!/bin/bash
"exec" "snakemake" "--jobs" "100" "--snakefile" "$0" "--latency-wait" "120" "--cluster" "qsub -l mem_free=17G,h_vmem=18G,h_fsize=20G"

#"exec" "snakemake" "--printshellcmds" "--snakefile" "$0" "--jobs" "40" "--latency-wait" "240"

import glob
import os.path
import itertools

SOURCE_DIR = '../../_m'
EXT = '.bam'


def sample_dict_iter(path, ext):
    for filename in glob.iglob(path+'/*'+ext):
        sample = os.path.basename(filename)[:-len(ext)]

        if 'bulk' not in sample:
            yield sample, {'filename': filename}


SAMPLE_DICT = {k:v for k,v in sample_dict_iter(SOURCE_DIR, EXT)}

#insure errors propogate along pipe'd shell commands
shell.prefix("set -o pipefail; ")

rule all:
    input:
        expand('../_m/{sample}.bam', sample=SAMPLE_DICT.keys())

rule rmdup:
    input:
        lambda x: SAMPLE_DICT[x.sample]['filename']

    output:
        '../_m/{sample}.bam'
    log:
        stderr = '{sample}.stderr',
        stdout = '{sample}.stdout'
    shell:
        '''
    export PERL5LIB=$HOME'/perl5/lib/perl5/'
    export PATH=$HOME'/.local/bin:'$PATH

    ../_h/slavseq_rmdup_hts.pl {input} {output}
       ''' 
