#!/bin/bash -e

# -*- coding: utf-8 -*-
# SLURM job script for run RStudio into Singularity container
# The Advanced Research Computing at Hopkins (ARCH)
# Ricardo S Jacomini < rdesouz4 @ jhu.edu >
# Date: Feb, 2 2022

# reference: https://dl.acm.org/doi/fullHtml/10.1145/3437359.3465569
# How to compile it
# git clone https://github.com/TACC/core_usage.git
##
# ml intel/2021
# export CPATH=/usr/include/:/cm/shared/apps/Intel/2021/intelpython/python3.9/include:$CPATH
# export LD_LIBRARY_PATH=/cm/shared/apps/Intel/2021/intelpython/python3.9/lib/:${LD_LIBRARY_PATH}

# /cm/shared/apps/Intel/2021-bk-3-18-22/compiler/2021.4.0/linux/bin/intel64/icpc -O2 -o .core_usage.intel  /home/rdesouz4/src/core_usage/core_usage.cpp -lX11 -lncurses -ltinfo

export LD_LIBRARY_PATH=/cm/shared/apps/Intel/2021-bk-3-18-22/intelpython/python3.7/lib/:${LD_LIBRARY_PATH}
export TERMINFO=/usr/share/terminfo
export TERM=linux
sudo clear

if [ -z $1 ]
then
    if [ -z $DISPLAY ]
    then
        echo -e "\nFail to open DISPLAY. Did you set up X11 forwarding? \n"
        echo -e "\nlogin into Rockfish: ssh -XY <userid>@login.rockfish.jhu.edu \n"
        echo -e "\nUsage:    core_usage [txt] \n"
        echo -e "\n          core_usage [t_interval] [txt] \n"

        echo -e "\nto save core usage info into log file:  \n"
        echo -e "\n     export LOG_CORE_USAGE=1  \n"
        echo -e "\nbefore running core_usage.  \n"
    else
      /data/apps/helpers/.core_usage.intel 1.0
    fi
else
      /data/apps/helpers/.core_usage.intel 1.0 $1
fi
